<?php

$states = [
    [ "alpha2" => "al", "name" => "Alabama" ],
    [ "alpha2" => "ak", "name" => "Alaska" ],
    [ "alpha2" => "az", "name" => "Arizona" ],
    [ "alpha2" => "ar", "name" => "Arkansas" ],
    [ "alpha2" => "ca", "name" => "California" ],
    [ "alpha2" => "co", "name" => "Colorado" ],
    [ "alpha2" => "ct", "name" => "Connecticut" ],
    [ "alpha2" => "de", "name" => "Delaware" ],
    [ "alpha2" => "dc", "name" => "District of Columbia" ],
    [ "alpha2" => "fl", "name" => "Florida" ],
    [ "alpha2" => "ga", "name" => "Georgia" ],
    [ "alpha2" => "hi", "name" => "Hawaii" ],
    [ "alpha2" => "id", "name" => "Idaho" ],
    [ "alpha2" => "il", "name" => "Illinois" ],
    [ "alpha2" => "in", "name" => "Indiana" ],
    [ "alpha2" => "ia", "name" => "Iowa" ],
    [ "alpha2" => "ks", "name" => "Kansas" ],
    [ "alpha2" => "ky", "name" => "Kentucky" ],
    [ "alpha2" => "la", "name" => "Louisiana" ],
    [ "alpha2" => "me", "name" => "Maine" ],
    [ "alpha2" => "md", "name" => "Maryland" ],
    [ "alpha2" => "ma", "name" => "Massachusetts" ],
    [ "alpha2" => "mi", "name" => "Michigan" ],
    [ "alpha2" => "mn", "name" => "Minnesota" ],
    [ "alpha2" => "ms", "name" => "Mississippi" ],
    [ "alpha2" => "mo", "name" => "Missouri" ],
    [ "alpha2" => "mt", "name" => "Montana" ],
    [ "alpha2" => "ne", "name" => "Nebraska" ],
    [ "alpha2" => "nv", "name" => "Nevada" ],
    [ "alpha2" => "nh", "name" => "New Hampshire" ],
    [ "alpha2" => "nj", "name" => "New Jersey" ],
    [ "alpha2" => "nm", "name" => "New Mexico" ],
    [ "alpha2" => "ny", "name" => "New York" ],
    [ "alpha2" => "nc", "name" => "North Carolina" ],
    [ "alpha2" => "nd", "name" => "North Dakota" ],
    [ "alpha2" => "oh", "name" => "Ohio" ],
    [ "alpha2" => "ok", "name" => "Oklahoma" ],
    [ "alpha2" => "or", "name" => "Oregon" ],
    [ "alpha2" => "pa", "name" => "Pennsylvania" ],
    [ "alpha2" => "pr", "name" => "Puerto Rico" ],
    [ "alpha2" => "ri", "name" => "Rhode Island" ],
    [ "alpha2" => "sc", "name" => "South Carolina" ],
    [ "alpha2" => "sd", "name" => "South Dakota" ],
    [ "alpha2" => "tn", "name" => "Tennessee" ],
    [ "alpha2" => "tx", "name" => "Texas" ],
    [ "alpha2" => "vi", "name" => "US Virgin Islands" ],
    [ "alpha2" => "ut", "name" => "Utah" ],
    [ "alpha2" => "vt", "name" => "Vermont" ],
    [ "alpha2" => "va", "name" => "Virginia" ],
    [ "alpha2" => "wa", "name" => "Washington" ],
    [ "alpha2" => "wv", "name" => "West Virginia" ],
    [ "alpha2" => "wi", "name" => "Wisconsin" ],
    [ "alpha2" => "wy", "name" => "Wyoming" ],
];

foreach ($states as $key => $json) {
    $json['alpha2'] = strtoupper($json['alpha2']);

    file_put_contents(__DIR__.'/state/'.($key + 1).'.json', json_encode($json));
}

exit(print_r($states));
